// Catálogo de BUSINESS_RULES.md §"Códigos de error de la API". Un solo lugar para API y web.
export const ERROR_HTTP_STATUS = {
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  CONSENT_REQUIRED: 409,
  QUOTA_FULL: 409,
  TASKS_LOCKED: 409,
  INCOMPLETE_RESULTS: 409,
  SESSION_CLOSED: 409,
  PLAN_NOT_READY: 409,
  PLAN_CLOSED: 409,
  OPEN_SESSIONS: 409,
  VERSION_CONFLICT: 409,
  ALREADY_APPROVED: 409,
  SEVERITY_ZERO_NO_STORY: 409,
  FINDING_LOCKED: 409,
  CAPACITY_EXCEEDED: 409,
  SPRINT_ALREADY_ACTIVE: 409,
  SPRINT_NOT_CLOSED: 409,
  POINTS_REQUIRED: 409,
  TOO_MANY_FILES: 409,
  FILE_TOO_LARGE: 413,
  INVALID_FILE_TYPE: 415,
  AI_PROVIDER_ERROR: 502,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_HTTP_STATUS;

export const ERROR_CODES = Object.keys(ERROR_HTTP_STATUS) as [ErrorCode, ...ErrorCode[]];
